apps/blog/api/urls.py
from django.conf.urls import url
from apps.blog.api.views import (
    BlogListAPIView,
    BlogDetailAPIView,
    BlogUpdateAPIView,
    BlogDeleteAPIView,
    BlogCreateAPIView,
)

app_name = 'blogs-api'
urlpatterns = [
    url(r'^$', BlogListAPIView.as_view(), name='all'),
    url(r'^(?P<slug>[\w-]+)$', BlogDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit$', BlogUpdateAPIView.as_view(), name='update'),
    url(r'^create$', BlogCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/delete$', BlogDeleteAPIView.as_view(), name='delete')
]

apps/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blogs'
urlpatterns = [
    url(r'^$', views.allblogs, name='all'),
    url(r'^(?P<slug>[\w-]+)$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit$', views.update, name='update'),
    url(r'^blog/create$', views.create, name='create'),
    url(r'^(?P<slug>[\w-]+)/delete$', views.delete, name='delete')
]

portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.accounts.views import login_view, register_view, logout_view
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.work.urls')),
    url(r'^blog/', include('apps.blog.urls', namespace="blogs")),
    url(r'^comment/', include('apps.comments.urls', namespace="comments")),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^api/users/', include('apps.accounts.api.urls', namespace="users-api")),
    url(r'^api/blog/', include('apps.blog.api.urls', namespace="blogs-api")),
    url(r'^api/comments/', include('apps.comments.api.urls', namespace="comments-api")),
    url(r'^api/auth/token/', obtain_jwt_token, name='create-token'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown
from ..comments.models import Comment

from .utils import get_read_time
# Create your models here.


class BlogManager(models.Manager):
    def active(self, *args, **kwargs):
        # Same as Blog.objects.all() = super(BlogManager, self).all()
        return super(BlogManager, self).filter(draft=False).filter(pub_date__lte=timezone.now())


class Blog(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="blogs", default=1, on_delete=models.CASCADE)
    pub_date = models.DateField(auto_now=False, auto_now_add=False)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    video = models.CharField(max_length=5000, blank=True)
    body = models.TextField()
    slug = models.SlugField(max_length=150, unique=True)
    draft = models.BooleanField(default=False)
    read_time = models.TimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BlogManager()

    def __str__(self):
        return self.title

    def get_html(self):
        content = self.body
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    # def date_only(self):
    #     return self.pub_date.strftime('%e %b %Y')

    def get_absolute_url(self):
        return reverse("blogs:detail", kwargs={"slug": self.slug})
        # return "/blog/%s" % self.id

    def get_api_url(self):
        return reverse("blogs-api:detail", kwargs={"slug": self.slug})

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_blog_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.body:
        html_string = instance.get_html()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_blog_receiver, sender=Blog)

apps/blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Blog
from pagedown.widgets import PagedownWidget


class BlogForm(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget(show_preview=False), label='Content')
    pub_date = forms.DateField(widget=forms.SelectDateWidget(
        attrs={'class': 'd-inline-block col-md-3 col-sm-3'}),
        label='Publish Date')

    class Meta:
        model = Blog

        fields = [
            "title",
            "image",
            "video",
            "body",
            "draft",
            "pub_date",
        ]
        labels = {
            'pub_date': 'Publish Date',
            'title': 'Blog Title',
            'video': 'Video Link',
            'body': 'Content',
        }

        widgets = {
            "image": forms.ClearableFileInput(
                attrs={'class': "form-control mb-2 round"}
            ),
        }

apps/blog/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,  # use ?search=, can chain with ?q= search
    OrderingFilter  # shows ordering of search, descending/ascending
)
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    CreateAPIView,
    RetrieveUpdateAPIView,
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)
from .pagination import BlogLimitOffsetPagination, BlogPageNumberPagination

from apps.blog.models import Blog

from .permissions import IsOwnerOrReadOnly

from .serializers import (
    BlogDetailSerializer,
    BlogListSerializer,
    BlogCreateUpdateSerializer,
)


class BlogCreateAPIView(CreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogCreateUpdateSerializer
    # permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class BlogListAPIView(ListAPIView):
    serializer_class = BlogListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    permission_classes = [AllowAny]
    search_fields = ['title', 'body', 'user__first_name']
    pagination_class = BlogPageNumberPagination  # PageNumberPagination

    def get_queryset(self, *args, **kwargs):
        # blogs_list = super(BlogListAPIView, self).get_queryset(*args, **kwargs)
        blogs_list = Blog.objects.all()
        query = self.request.GET.get('q')
        if query:
            blogs_list = blogs_list.filter(
                Q(title__icontains=query) |
                Q(body__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()
        return blogs_list


class BlogDetailAPIView(RetrieveAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogDetailSerializer
    permission_classes = [AllowAny]
    lookup_field = "slug"


class BlogUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogCreateUpdateSerializer
    lookup_field = "slug"

    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class BlogDeleteAPIView(DestroyAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogDetailSerializer
    lookup_field = "slug"
    permission_classes = [IsOwnerOrReadOnly]

apps/blog/views.py
try:
    from urllib.parse import quote_plus  # Converts string into url format
except:
    pass
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.utils import timezone

from .forms import BlogForm
from .models import Blog
from .utils import get_header_text
from ..comments.forms import CommentForm
from ..comments.models import Comment
# Create your views here.


def allblogs(request):
    today = timezone.now().date()
    blogs_list = Blog.objects.active().order_by('-pub_date')
    if request.user.is_staff or request.user.is_superuser:
        blogs_list = Blog.objects.all().order_by('-pub_date')

    query = request.GET.get('q')
    if query:
        blogs_list = blogs_list.filter(
            Q(title__icontains=query) |
            Q(body__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(blogs_list, 2)  # Show 25 contacts per page
    page_variable = "page"
    page = request.GET.get(page_variable)
    blogs = paginator.get_page(page)

    context = {
        'blogs': blogs,
        'today': today,
        'page_variable': page_variable,
        'header_text': get_header_text,

    }
    return render(request, "blog/list.html", context)


def detail(request, slug=None):
    instance = get_object_or_404(Blog, slug=slug)
    if instance.draft or instance.pub_date > timezone.now().date():
        if not request.user.is_staff:
            raise Http404
    # Converting string into url
    share_quote = quote_plus(instance.body)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated:
        c_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get("object_id")
        content_data = comment_form.cleaned_data.get("content")
        # Make sure parent obj is there
        parent_obj = None
        # check/parse to see if parent id is there
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        # check if the parent id is in the database,
        # if it exists, we set the parent obj to be the first item in qs
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return redirect(new_comment.content_object.get_absolute_url())

    # This gives all the comments using BlogManager
    comments = instance.comments  # Getting the comments as a property vs qs - Comment.objects.filter_by_instance(blog)
    context = {
        'blog': instance,
        'share_quote': share_quote,
        'comments': comments,
        'comment_form': comment_form,
        'header_text': get_header_text

    }
    return render(request, 'blog/detail.html', context)


def create(request):
    if not request.user.is_staff:
        messages.error(request, "Admin must grant permission to create blog.")
        raise Http404('Admin must grant permission to create blog.')

    if not request.user.is_authenticated:
        messages.error(request, "Must be registered/logged in.")
        raise Http404('Must be registered/logged in.')

    form = BlogForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # message success
        messages.success(request, "Successfully created.")
        return redirect(instance.get_absolute_url())
    context = {
        "form": form,
        "header_text": get_header_text
    }
    return render(request, 'blog/form.html', context)


def update(request, slug=None):
    if not request.user.is_staff:
        messages.error(request, 'Must be logged in and must be your own blog.')
        raise Http404('Must be logged in and must be your own blog.')
    if request.user.username != Blog.objects.get(slug=slug).user.username:
        messages.error(request, 'You could only edit your own blogs!')
        raise Http404('You could only edit your own blogs!')
    instance = get_object_or_404(Blog, slug=slug)
    form = BlogForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():

        instance = form.save(commit=False)
        instance.save()
        # message success
        messages.success(request, "Blog updated.", extra_tags='html_safe')
        return redirect(instance.get_absolute_url())
    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
        'header_text': get_header_text
    }
    return render(request, "blog/form.html", context)


def delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        messages.error(request, 'You could only delete your blogs!')
        raise Http404('You could only delete your blogs!')
    instance = get_object_or_404(Blog, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted.")
    return redirect("blogs:all")

apps/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}#1 Source for my REAL Thoughts{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}" media="screen" title="no title" charset="utf-8">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- Django-Pagedown -->
    <style>
        {% block style %}{% endblock style%}
    </style>
    {% block head_extra %}{% endblock head_extra %}

</head>
<body>
<header>
    <div class="scroll-top-wrapper">
        <span class="scroll-top-inner">
            <i class="fa fa-2x fa-chevron-up"></i>
        </span>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">William Tran</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto text-right">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://github.com/wtran29">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% static 'work/images/resume2018v3.pdf' %}">Resume</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/blog">Billy's Resources</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="mailto:wtran4hire@gmail.com">Contact</a>
                </li>
            </ul>
            <!--<form class="form-inline my-2 my-lg-0">-->
            <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
            <!--</form>-->
        </div>
    </nav>
</header>
<section class="jumbotron jumbotron-fluid text-center">
    <div class="container">
        <h1 class="jumbotron-heading display-4 font-weight-bold">Billy's Resources</h1>
        <p class="header-text">{{ header_text|random }}</p>
    </div>
</section>
<div id="fb-root"></div>
<!--https://developers.facebook.com/docs/plugins/like-button-->
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{% include "blog/messages.html" %}
<div class="container">
    {% if request.user.is_authenticated %}<p class="lead text-right">Signed in as {{ request.user }}</p>{% endif %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'blogs:all' %}">Blogs</a></li>
        {% block blog_detail_link %}
        {% endblock %}
        {% if not request.user.is_authenticated %}
        <li class="breadcrumb-item ml-auto"><a href="{% url 'register' %}">Register</a></li>
        <li class="breadcrumb-item"><a href="{% url 'login' %}">Login</a></li>
        {% else %}
        <li class="breadcrumb-item ml-auto"><a href="{% url 'blogs:create' %}">Create</a></li>
        <li class="breadcrumb-item"><a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
    </ol>
</div>
<div class="blog-content container">
    {% block content %}
    {% endblock content %}
</div>
<div class="text-center">
    <a href="https://partners.uber.com/i/ppyekzxug"><img class="img-fluid rounded" src="{% static 'blog/images/uber-invite.jpg' %}" width="800"></a>
</div>
<section id="connect">
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-md-12 pt-5">
                <h3 class="text-center pb-3">Connect with me</h3>
                <div class="mb-5 text-center">
                    <a style="color: gray; text-decoration: none;" href="mailto:wtran4hire@gmail.com">
                        <i class="fas fa-envelope fa-lg white-text mr-md-5 mr-3 fa-5x"></i>
                    </a>
                    <a style="color: navy; text-decoration: none;" href="https://www.linkedin.com/in/william-tran">
                        <i class="fab fa-linkedin fa-lg white-text mr-md-5 mr-3 fa-5x"></i>
                    </a>
                    <a style="color: black; text-decoration: none;" href="https://github.com/wtran29">
                        <i class="fab fa-github-alt fa-lg white-text mr-md-5 mr-3 fa-5x"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<footer class="page-footer font-small text-muted pt-2">
    <div class="container py-1">
        <!--<p class="float-right">-->
        <!--<a href="#">Back to top</a>-->
        <!--</p>-->
        <p>William Tran &copy; {% now "Y" %} Copyright</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.0/marked.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>

<script type="text/javascript">
<!--Markdown function-->
<!--Show markdowns correctly-->
<!--Show markdown images correctly-->
$(document).ready(function(){
    $(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
    })

    $(".blog-detail-item img").each(function(){
        $(this).addClass("img-responsive").attr('width', '100%')
    })


    var contentInput = $("#id_body");

    function setContent(value){
        console.log(value)
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive").attr('width', '100%')
        })
    }
    setContent(contentInput.val())

    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })

    var titleInput = $("#id_title");

    function setTitle(value){
        if (value) {
            $("#preview-title").text(value);
        }
    }
    setTitle(titleInput.val())

    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })

    function readURL(input) {

      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
          $('#preview-image').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#id_image").change(function() {
      readURL(this);
    });

    var videoInput = $("#id_video");

    function setVideo(value){
        if(value){
            $("#preview-video").attr('src', value);
        }
    }
    setVideo(videoInput.val())

    videoInput.keyup(function(){
        var newContent = $(this).val()
        setVideo(newContent)
    })

    // preview-title
    // preview-content
})

$(document).ready(function(){
    $(".comment-show-btn").click(function(event){
        event.preventDefault();
        $(this).parent().parent().parent().next(".comment-reply").fadeToggle();
    })

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().parent().parent().next(".comment-reply").fadeToggle();
    })
})


<!--Scroll top function-->
$(function(){

    $(document).on( 'scroll', function(){

        if ($(window).scrollTop() > 100) {
            $('.scroll-top-wrapper').addClass('show');
        } else {
            $('.scroll-top-wrapper').removeClass('show');
        }
    });
});

$(function(){

$(document).on( 'scroll', function(){

if ($(window).scrollTop() > 100) {
$('.scroll-top-wrapper').addClass('show');
} else {
$('.scroll-top-wrapper').removeClass('show');
}
});

$('.scroll-top-wrapper').on('click', scrollToTop);
});

function scrollToTop() {
verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;
element = $('body');
offset = element.offset();
offsetTop = offset.top;
$('html, body').animate({scrollTop: offsetTop}, 500, 'linear');
}

$(function () {
  $('[data-toggle="popover"]').popover({
    trigger: 'focus'
  })
})
</script>
</body>
</html>

apps/blog/templates/blog/form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="row">

    <div class="col-sm-6">
        <h1>Preview</h1>
        <div class="content-preview">
            <h3 class="pt-4" id="preview-title"></h3>
            {% if instance.image %}
            <img class="img-responsive" src="{{ instance.image.url }}" width="100%"/>
            {% endif %}
            <img class="img-responsive" id="preview-image" src="" width="100%"/>
            <br>
            {% if instance.video %}
            <iframe class="img-responsive" id="preview-video" width="100%" height="350" src="" frameborder="0"
                allow="autoplay; encrypted-media" allowfullscreen></iframe>
            {% endif %}
            <p id="preview-content"></p>
        </div>
    </div>

    <div class="col-sm-6">
        <h1>Create Blog</h1>

        <form class="py-4" method="post" action="" enctype='multipart/form-data'>
            {% csrf_token %}

            {{ form|crispy }}
            <button class="btn btn-secondary my-2" type="submit">{% if instance %}Update{% else %}Create{% endif %}</button>
            {% if instance %}
            <a href="{{ instance.get_absolute_url }}/delete" class="btn btn-danger" role="button">Delete</a>
            {% endif %}
        </form>

    </div>

</div>
<hr>
{% endblock content %}

apps/blog/templates/blog/messages.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}